#!/bin/bash
#  ____                              
# | __ ) ___ _ ____      ___ __ ___  
# |  _ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |____/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      

# Configuration file for Bspwm

# AUTOSTART
# =====================================================================================

# Polybar
killall polybar
polybar --config=~/.config/polybar/config-bspwm.ini main &
polybar --config=~/.config/polybar/config-bspwm.ini secondary &

# Sxhkd
killall sxhkd
sxhkd &

# Picom
picom &

# Nm-Applet
nm-applet &

# Wallpaper
feh --bg-fill ~/Images/Wallpapers/wallpaper

# Keyboard Layout
setxkbmap fr

# Monitor configuration
~/.screenlayout.sh

# CONFIGURATION
# =====================================================================================

# Workspaces
bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor VGA1 -d I II III IV V

# Borders & gaps
bspc config border_width			2
bspc config window_gap				15

# Colors
bspc config focused_border_color	"#d3dae3"
bspc config normal_border_color	"#4b5164"


# Split ratio
bspc config split_ratio				0.50

# Monocle config
bspc config borderless_monocle	true
bspc config gapless_monocle		true

# Focus follows pointer
bspc config focus_follows_pointer true
